name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're facing
      placeholder: |
        I need to be able to validate YAML against a JSON schema, but currently there's no built-in way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        Add a new ValidateSchema() function that takes a schema definition and validates the YAML structure...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design
      description: If applicable, show how you envision the API would look
      render: go
      placeholder: |
        // Example of how the feature might be used
        schema := &yaml.Schema{
            Type: "object",
            Properties: map[string]*yaml.Schema{
                "name": {Type: "string"},
            },
        }

        errors := yaml.ValidateSchema(tree, schema)
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        - Using external validation libraries
        - Writing custom validation logic
        - ...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to existing APIs?
      options:
        - No breaking changes needed
        - Minor breaking changes acceptable
        - Major breaking changes required
        - Not sure
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Validating configuration files before processing
        2. Ensuring YAML files conform to a specific structure
        3. ...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how this could be implemented, please share
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true
        - label: This feature aligns with the project's goals
          required: false